import os
from dotenv import load_dotenv

load_dotenv(override=True)

SENDGRID_API_KEY = os.getenv("SENDGRID_API_KEY", "").strip()
APP_URL = os.getenv("APP_URL", "http://localhost:8501").strip()
FROM_EMAIL = "noreply@neurotriage-ai.com"


def send_stroke_alert(
    doctor_email: str,
    doctor_name: str,
    patient_name: str,
    patient_id: str,
    confidence: float,
    scan_date: str,
) -> bool:
    """
    Sends an urgent HTML stroke alert email via SendGrid.

    Returns True on success, False on failure (e.g. missing key, API error).
    """
    if not SENDGRID_API_KEY:
        print("[email_utils] SENDGRID_API_KEY not set — skipping email.")
        return False

    try:
        from sendgrid import SendGridAPIClient
        from sendgrid.helpers.mail import Mail, Content

        subject = f"URGENT: Stroke Detected \u2014 {patient_name}"

        html_body = f"""
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8"/>
  <style>
    body {{ font-family: Arial, sans-serif; background:#f4f4f4; margin:0; padding:0; }}
    .wrapper {{ max-width:600px; margin:30px auto; background:#fff; border-radius:8px; overflow:hidden; box-shadow:0 4px 12px rgba(0,0,0,0.1); }}
    .header {{ background:#E24B4A; padding:24px 32px; }}
    .header h1 {{ color:#fff; margin:0; font-size:22px; letter-spacing:1px; }}
    .header p {{ color:rgba(255,255,255,0.85); margin:4px 0 0; font-size:13px; }}
    .body {{ padding:32px; color:#333; }}
    .info-table {{ width:100%; border-collapse:collapse; margin:20px 0; }}
    .info-table td {{ padding:10px 14px; border-bottom:1px solid #eee; font-size:14px; }}
    .info-table td:first-child {{ font-weight:700; color:#555; width:40%; }}
    .confidence {{ font-size:28px; font-weight:700; color:#E24B4A; text-align:center; margin:20px 0; }}
    .cta {{ text-align:center; margin:28px 0; }}
    .cta a {{ background:#E24B4A; color:#fff; padding:12px 28px; border-radius:6px; text-decoration:none; font-weight:700; font-size:15px; }}
    .footer {{ background:#f9f9f9; padding:16px 32px; font-size:11px; color:#999; text-align:center; border-top:1px solid #eee; }}
  </style>
</head>
<body>
  <div class="wrapper">
    <div class="header">
      <h1>&#x26A0;&#xFE0F; URGENT STROKE ALERT</h1>
      <p>NeuroTriage AI Clinical Decision Support System</p>
    </div>
    <div class="content">
      <p><strong>URGENT NOTIFICATION</strong></p>
      <p>Dear <strong>Dr. {doctor_name}</strong>,</p>
      <p>The NeuroTriage AI system has detected a <strong>high-confidence stroke</strong> in a recent CT scan. Immediate review is required.</p>

      <table class="info-table">
        <tr><td>Patient Name</td><td>{patient_name}</td></tr>
        <tr><td>Patient ID</td><td>{patient_id}</td></tr>
        <tr><td>Scan Date</td><td>{scan_date}</td></tr>
        <tr><td>AI Classification</td><td><strong style="color:#E24B4A;">STROKE DETECTED</strong></td></tr>
      </table>

      <div class="confidence">{confidence * 100:.1f}% Confidence</div>

      <p style="text-align:center; color:#555;">Please review the full AI analysis report in the NeuroTriage AI system immediately.</p>

      <div class="cta">
        <a href="{APP_URL}/Patient_History">Review Patient History &rarr;</a>
      </div>
    </div>
    <div class="footer">
      <strong>DISCLAIMER:</strong> This alert is generated by an AI decision-support tool (NeuroTriage AI)
      and must be reviewed by a qualified radiologist before any clinical decision.
      Not for standalone diagnostic use.
    </div>
  </div>
</body>
</html>
"""

        message = Mail(
            from_email=FROM_EMAIL,
            to_emails=doctor_email,
            subject=subject,
            html_content=Content("text/html", html_body),
        )

        sg = SendGridAPIClient(SENDGRID_API_KEY)
        response = sg.send(message)
        print(f"[email_utils] Alert sent to {doctor_email} — status {response.status_code}")
        return response.status_code in (200, 202)

    except Exception as e:
        print(f"[email_utils] Failed to send alert: {e}")
        return False
