[server]
port = 8501
headless = true
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[theme]
base = "dark"
primaryColor = "#00f2fe"
backgroundColor = "#050505"
secondaryBackgroundColor = "#0a0a0a"
textColor = "#ffffff"
font = "sans serif"
